codecov:
  # Ne pas inclure le token dans les fichiers source
  # Utilisez les variables d'environnement CI à la place

coverage:
  precision: 2
  round: down
  range: "50...100"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

github_checks:
  annotations: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: true
