version: '3.8'

services:
  vat_recovery:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/credentials.json
    volumes:
      - .:/app
