name: Run OCR test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write Google credentials to file
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" | jq '.' > credentials.json

    - name: Run tests
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
        PYTHONPATH: ${{ github.workspace }}/app
      run: |
        pytest
